version: "1.0"
# docker-compose up -d -f docker-compose.yml

# 使用创建好的网络，而不是让docker-compose自己创建网络
networks:
  app-net:
    name: app-net

# docker-compose 创建网卡
#networks:
#  app-net:
#    driver: bridge

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    networks:
      - app-net
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes" #允许空密码登录
    volumes:
      -  ./redis/data:/bitnami/redis/data

  etcd-server:
    image: bitnami/etcd:3.4.18
    container_name: etcd-server
    restart: always
    networks:
      - app-net
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd-server:2379"

  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: elasticsearch
    restart: always
    networks:
      - app-net
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  # es的web管理界面
  elasticsearch-head:
    image: mobz/elasticsearch-head:5-alpine
    container_name: elasticsearch-head
    restart: always
    networks:
      - app-net
    ports:
      - 9100:9100

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: always
    networks:
      - app-net
    ports:
      - 16686:16686
      - 14268:14268 #UDP  agent发送jaeger.thrift格式数据
      - 5775:5775 #UDP  接收兼容zipkin的协议数据
      - 6831:6831 #UDP  接收兼容jaeger的兼容协议
      - 5778:5778 #http 数据量大不建议使用
      - 9411:9411
    environment: #如果要依赖elasticsearch，请打开下面的配置
      SPAN_STORAGE_TYPE: "elasticsearch" #配置elasticsearch 作为存储
      ES_SERVER_URLS: "http://elasticsearch:9200" #配置elasticsearch 作为存储
    depends_on:
      - elasticsearch


#  kibana:
#    image: kibana:7.16.1
#    container_name: kibana
#    restart: always
#    networks:
#      - app-net
#    ports:
#      - 5601:5601
#    environment:
#      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
#    volumes:
#      - ./kibana/config:/usr/share/kibana/config #配置文件挂载
#    depends_on:
#      - elasticsearch
##
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    container_name: zookeeper
#    restart: always
#    networks:
#      - app-net
#    ports:
#      - 2181:2181
#    environment:
#      ALLOW_ANONYMOUS_LOGIN: yes
#
#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    restart: always
#    networks:
#      - app-net
#    ports:
#      - 9092:9092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
#      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
#      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      ALLOW_PLAINTEXT_LISTENER: "yes"
#      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
#    depends_on:
#      - zookeeper
