# debug模式
debug = true
# 日志文件路径
log_path = ""

# http 监听端口
[http]
# 监听地址
address = "0.0.0.0"
# 监听端口
port = 10280

# 一下每一个server为一个etcd服务 ##
[[server]]
# 显示名称
title = "docker etcd server"
# 标识名
name = "local"
# etcd连接地址 如果为集群请填写全部地址
address = ["http://etcd-server:2379"]
# 查看的key前缀
key_prefix = ""
# 简述信息
desc = "docker"
# 可访问服务器角色列表 - 不写则为所有用户可访问
roles = ["admin"]

#[[server]]
#title = "本机"
#name = "local"
#address = ["http://etcd-server:2379"]
#key_prefix = "root"
#desc = "本机环境"
#roles = ["admin","dev"]

## 以下为用户列表 ##
[[user]]
username = "admin"
password = "123456"
role = "admin"

[[user]]
username = "dev_user"
password = "123456"
role = "dev"
